[project]
name = "disco"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncache>=0.3.1",
    "cachetools>=5.5.2",
    "discord>=2.3.2",
    "dotenv>=0.9.9",
    "requests>=2.32.3",
]
