name: Restart Disco Service

on:
  push:
    branches:
      - master

jobs:
  restart-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restart Disco Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: $${ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.USERNAME }}
          script: |
            sudo systemctl restart disco.service
